language: node_js
cache: npm
notifications:
  email: false
node_js:
  - lts/*
  - node
install: npm install
branches:
  only:
    - master
    - develop
    - beta
    - alpha

jobs:
  include:
    - stage: testing
      if: type != pull_request
      node_js: lts/*
      env:
        - TEST=test
      script:
        - npm run test
