version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - ./.env
    command: ['--requirepass ${REDIS_PASSWORD}']
